"""empty message

Revision ID: 3449299192b7
Revises: 5f486372bb36
Create Date: 2025-12-01 20:28:27.336354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3449299192b7'
down_revision = '5f486372bb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hero_1', sa.Integer(), nullable=True),
    sa.Column('hero_2', sa.Integer(), nullable=True),
    sa.Column('hero_3', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_queued', sa.Boolean(), nullable=True),
    sa.Column('is_challenger', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hero_1'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['hero_2'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['hero_3'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('battle_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('battle_losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('battle_losses')
        batch_op.drop_column('battle_wins')

    op.drop_table('line_up')
    # ### end Alembic commands ###
