"""empty message

Revision ID: 43f0745d1e22
Revises: cdfd5fd5caa0
Create Date: 2025-08-21 12:51:07.786081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f0745d1e22'
down_revision = 'cdfd5fd5caa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shop_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shopitem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shopitem_id'], ['shopitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shopitem_id')
    )
    op.drop_table('user_shopitems')
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=True))
        batch_op.drop_column('condition')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rolls_done', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rolls_done')
        batch_op.drop_column('tokens_spent')

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('value')
        batch_op.drop_column('type')

    op.create_table('user_shopitems',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('shopitem_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['shopitem_id'], ['shopitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shopitem_id')
    )
    op.drop_table('user_shop_items')
    # ### end Alembic commands ###
