"""empty message

Revision ID: 6068639f24a7
Revises: 1f0d680800ba
Create Date: 2025-11-15 11:33:42.458010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6068639f24a7'
down_revision = '1f0d680800ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_attack', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_defense', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_column('base_defense')
        batch_op.drop_column('base_attack')
        batch_op.drop_column('base_hp')

    # ### end Alembic commands ###
