"""empty message

Revision ID: 720fb01becf0
Revises: 43f0745d1e22
Create Date: 2025-08-21 13:12:59.031101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720fb01becf0'
down_revision = '43f0745d1e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopitem')
    op.drop_table('user_shop_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shop_items',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('shopitem_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['shopitem_id'], ['shopitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shopitem_id')
    )
    op.create_table('shopitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
