"""empty message

Revision ID: b9f005230a7e
Revises: 3449299192b7
Create Date: 2025-12-02 12:18:37.010078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f005230a7e'
down_revision = '3449299192b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_battle_log', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_battle_winner', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_battle_loser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_battle_unseen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_up', schema=None) as batch_op:
        batch_op.drop_column('last_battle_unseen')
        batch_op.drop_column('last_battle_loser')
        batch_op.drop_column('last_battle_winner')
        batch_op.drop_column('last_battle_log')

    # ### end Alembic commands ###
